version: '3'

services:

  backend:
    container_name: reactive-atdd-workshop-backend
    build:
      context: ./backend
      #dockerfile: Dockerfile
    image: reactive-atdd-workshop-backend
    restart: always
    ports:
      - "8081:8080"
    tty: true

  frontend:
    container_name: reactive-atdd-workshop-frontend
    build:
      context: ./frontend
    image: reactive-atdd-workshop-frontend
    restart: always
    ports:
      - "8080:3000"
    tty: true