version: '3'

services:

  backend:
    container_name: reactive-atdd-workshop-backend
    build:
      context: ./backend
      #dockerfile: Dockerfile
    image: reactive-atdd-workshop
    restart: always
    ports:
      - "8080:8080"
    tty: true