name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - README.md
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle, leveraging on Makefile
      run: make test
    - name: Generate Jacoco report
      run: gradle jacocoTestReport
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        flags: unittests
    - name: Container tests
      run: |
        make container-start
        ./healthcheck.sh
