name: Quality Assurance

on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - README.md
    branches:
      - main

jobs:
  functional_tests:
    # this step runs the project's functional tests using gradle test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: SSet up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
#      - name: Cache mvn dependencies
#        uses: actions/cache@v2.1.4
#        env:
#          cache-name: mvn-deps
#        with:
#          path: ~/.m2
#          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
#          restore-keys: ${{ env.cache-name }}-
      - name: Test
        run: gradle test
      - name: Generate Jacoco report
        run: gradle jacocoTestReport
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests